#!/usr/bin/env python3
"""Generate the run sheet: when each module should start, and what to cut if late.

Marp's presenter view already shows elapsed time. What it cannot know is whether that
elapsed time is good or bad. With five presenters sharing a hard 60-minute ceiling, the
useful number is not "23 minutes have passed" but "you should have handed over at 22".

The budget is read from the module divider of each slide file, from the tag the audience
also sees — `<span class="tag">Module 1 · 12 min</span>` — so the run sheet cannot drift
away from what is on the screen. Files with no such tag (backup slides) are skipped.

Usage: python3 tools/run-sheet.py slides/*.md -o build/run-sheet.md
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

TAG = re.compile(r'<span class="tag">\s*Module\s*(\d+)\s*·\s*(\d+)\s*min\s*</span>')
TITLE = re.compile(r"^# (.+)$", re.MULTILINE)
CUT = re.compile(r"^CUT IF LATE:\s*(.+)$", re.MULTILINE)


def parse(path: pathlib.Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    tag = TAG.search(text)
    if not tag:
        return None
    title = TITLE.search(text)
    cut = CUT.search(text)
    return {
        "number": int(tag.group(1)),
        "budget": int(tag.group(2)),
        "title": title.group(1).strip() if title else path.stem,
        "slides": sum(1 for line in text.splitlines() if line.strip() == "---") - 1,
        "cut": cut.group(1).strip() if cut else "— not decided —",
        "path": path,
    }


def hhmm(minutes: int, start_hour: int, start_minute: int) -> str:
    total = start_hour * 60 + start_minute + minutes
    return f"{total // 60 % 24:02d}:{total % 60:02d}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("sources", nargs="+", type=pathlib.Path)
    ap.add_argument("-o", "--output", required=True, type=pathlib.Path)
    ap.add_argument("--start", default="13:30", help="scheduled start, HH:MM")
    args = ap.parse_args()

    start_hour, start_minute = (int(x) for x in args.start.split(":"))

    modules = sorted(
        (m for m in (parse(p) for p in args.sources) if m),
        key=lambda m: m["number"],
    )
    if not modules:
        print("run-sheet.py: no module dividers found", file=sys.stderr)
        return 1

    rows, elapsed = [], 0
    for m in modules:
        rows.append((m, elapsed, elapsed + m["budget"]))
        elapsed += m["budget"]
    presented = elapsed

    out = [
        "# Run sheet — Alps technical training",
        "",
        f"Swiss AI Initiative Annual Meeting, Wednesday 26 August 2026. "
        f"Scheduled start **{args.start}** (may shift — if it does, use the T+ column, "
        "not the clock).",
        "",
        "Start the timer in the presenter view (press `p`, then click the timer on the "
        "right) at the moment module 0 begins. Everything below is measured from there.",
        "",
        "| # | Module | Budget | Starts | Ends | Clock | Slides |",
        "|---|---|---|---|---|---|---|",
    ]
    for m, begins, ends in rows:
        out.append(
            f"| {m['number']} | {m['title']} | {m['budget']} min | "
            f"T+{begins:02d}:00 | T+{ends:02d}:00 | "
            f"{hhmm(begins, start_hour, start_minute)} | {m['slides']} |"
        )
    out += [
        f"| — | **Open discussion** | 30 min | T+{presented:02d}:00 | "
        f"T+{presented + 30:02d}:00 | {hhmm(presented, start_hour, start_minute)} | — |",
        "",
        f"**Presentation total: {presented} minutes.** "
        + ("Over the 60-minute ceiling — fix this before the session."
           if presented > 60 else f"{60 - presented} minutes of slack against the ceiling."),
        "",
        "## If you are running late",
        "",
        "Check the timer at your own hand-off, not at the end. A module that overruns "
        "steals from the next presenter, who has no way to get it back. Each module has "
        "one pre-agreed cut, so the decision is made now and not on stage:",
        "",
    ]
    for m, _, _ in rows:
        out.append(f"- **Module {m['number']}** — {m['cut']}")
    out += [
        "",
        "## For whoever keeps time",
        "",
        "Sit where the presenters can see you. Show fingers for minutes remaining at "
        "T-3, T-2, T-1 of each module, not at the end of the hour. The whole point is "
        "that the last presenter still gets their three minutes.",
        "",
        f"_Generated by `tools/run-sheet.py` from the module dividers. "
        f"Change a budget in the slide tag and rerun `make runsheet`._",
    ]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"run-sheet.py: wrote {args.output} ({presented} min presented)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
